using System.Collections.Generic;

public static class BasicDecks {

    public static List<string> elementalistDeck = new List<string> {
        "Fireball",
        "Fireball",
        "Fireball",
        "Stone Skin",
        "Stone Skin",
        "Stone Skin",
        "Frost Nova",
        "Frost Nova",
        "Frost Nova",
        "Consult Notes",
        "Consult Notes",
        "Consult Notes",
        "Arcane Pulse",
        "Arcane Pulse",
        "Arcane Pulse",
        "Mana Bolt",
        "Mana Bolt",
        "Mana Bolt",
        "Mana Bolt",
        "Mana Bolt",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Meteor",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk"
    };

    public static List<string> fireElementalist = new List<string> {
        "Fireball",
        "Fireball",
        "Fireball",
        "Fireball",
        "Fireball",
        "Fireball",
        "Consult Notes",
        "Consult Notes",
        "Consult Notes",
        "Arcane Pulse",
        "Arcane Pulse",
        "Arcane Pulse",
        "Meteor",
        "Meteor",
        "Meteor",
        "Engulf",
        "Engulf",
        "Engulf",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk"
    };

    public static List<string> summonerElementalist = new List<string> {
        "Summon Imp",
        "Summon Imp",
        "Summon Imp",
        "Summon Imp",
        "Summon Imp",
        "Arcane Pulse",
        "Arcane Pulse",
        "Arcane Pulse",
        "Arcane Pulse",
        "Arcane Pulse",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk",
        "Walk"
    };

}